City.create!(name: "San Francisco", country: "USA", latitude: 37.7749, longitude: -122.4194)
City.create!(name: "Shanghai", country: "CHN", latitude: 31.2304, longitude: 121.473)
City.create!(name: "Karachi", country: "PAK", latitude: 24.8607, longitude: 67.0011)
City.create!(name: "Prague", country: "CZE", latitude: 50.0755, longitude: 14.4378)
City.create!(name: "Istanbul", country: "TUR", latitude: 41.0082, longitude: 28.9784)
City.create!(name: "Berlin", country: "DEU", latitude: 52.5200, longitude: 13.4050)


User.create!(first_name: "Robinho", last_name: "Sotoski", email: "robinho@robinho.com", password: "password", password_confirmation: "password", image_url: "", languages_spoken: "English, Spanish, French, Portuguese, Mandarin, Russian, Turkish")
User.create!(first_name: "Flomario", last_name: "Le Troublebuttz", email: "flomario@flomario.com", password: "password", password_confirmation: "password", image_url: "", languages_spoken: "English, Mandarin")
User.create!(first_name: "Zarru", last_name: "Le Bird", email: "zarru@zarru.com", password: "password", password_confirmation: "password", image_url: "", languages_spoken: "English, Urdu, Hindi, Gujarati")
User.create!(first_name: "Vojta", last_name: "Letalio", email: "vojta@vojta.com", password: "password", password_confirmation: "password", image_url: "", languages_spoken: "English, Czech")
User.create!(first_name: "Ayita", last_name: "Highjazzy", email: "ayita@ayita.com", password: "password", password_confirmation: "password", image_url: "", languages_spoken: "English, Arabic, Turkish, Spanish")
User.create!(first_name: "Clarious", last_name: "Meow", email: "clarious@clarious.com", password: "password", password_confirmation: "password", image_url: "", languages_spoken: "English, Spanish")

UserCity.create!(user_id: 1, city_id: 1, visited: "true", lived: "true", current_living: "true", current_visiting: "true")
UserCity.create!(user_id: 1, city_id: 2, visited: "true", lived: "true", current_living: "false", current_visiting: "false")
UserCity.create!(user_id: 2, city_id: 1, visited: "true", lived: "true", current_living: "true", current_visiting: "true")
UserCity.create!(user_id: 2, city_id: 2, visited: "true", lived: "true", current_living: "false", current_visiting: "false")
UserCity.create!(user_id: 3, city_id: 3, visited: "true", lived: "true", current_living: "false", current_visiting: "false")
UserCity.create!(user_id: 3, city_id: 4, visited: "false", lived: "false", current_living: "false", current_visiting: "false")
UserCity.create!(user_id: 4, city_id: 4, visited: "true", lived: "true", current_living: "true", current_visiting: "true")
UserCity.create!(user_id: 4, city_id: 1, visited: "true", lived: "true", current_living: "false", current_visiting: "false")
UserCity.create!(user_id: 5, city_id: 5, visited: "true", lived: "true", current_living: "false", current_visiting: "false")
UserCity.create!(user_id: 5, city_id: 6, visited: "true", lived: "true", current_living: "true", current_visiting: "true")
UserCity.create!(user_id: 6, city_id: 1, visited: "true", lived: "true", current_living: "true", current_visiting: "true")
UserCity.create!(user_id: 6, city_id: 2, visited: "false", lived: "false", current_living: "false", current_visiting: "false")

Connection.create!(sender_id: 1, recipient_id: 2, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 3, accepted: "true")
Connection.create!(sender_id: 2, recipient_id: 3, accepted: "true")
Connection.create!(sender_id: 2, recipient_id: 5, accepted: "true")
Connection.create!(sender_id: 3, recipient_id: 6, accepted: "true")
Connection.create!(sender_id: 4, recipient_id: 1, accepted: "false")
Connection.create!(sender_id: 5, recipient_id: 6, accepted: "false")
Connection.create!(sender_id: 6, recipient_id: 4, accepted: "true")

