City.create!(name: "San Francisco" , country: "USA" , latitude: "37.7749° N", longitude: "122.4194° W")
City.create!(name: "Shanghai" , country: "CHN" , latitude: "31.2304° N", longitude: "121.4737° E")
City.create!(name: "Karachi" , country: "PAK" , latitude: "24.8607° N", longitude: "67.0011° E")
City.create!(name: "Prague" , country: "CZE" , latitude: "50.0755° N", longitude: "14.4378° E")
City.create!(name: "Istanbul" , country: "TUR" , latitude: "41.0082° N", longitude: "28.9784° E")
City.create!(name: "Berlin" , country: "DEU" , latitude: "52.5200° N", longitude: "13.4050° E")


User.create!(first_name: "Robinho", last_name: "Sotoski", email: "robinho@robinho.com", password_digest: "", image_url: "", languages_spoken: ["English", "Spanish", "French", "Portuguese", "Mandarin", "Russian", "Turkish"])
User.create!(first_name: "Flomario", last_name: "Le Troublebuttz", email: "flomario@flomario.com", password_digest: "", image_url: "", languages_spoken: ["English", "Mandarin"])
User.create!(first_name: "Zarru", last_name: "Le Bird", email: "zarru@zarru.com", password_digest: "", image_url: "", languages_spoken: ["English", "Urdu", "Hindi", "Gujarati"])
User.create!(first_name: "Vojta", last_name: "Letalio", email: "vojta@vojta.com", password_digest: "", image_url: "", languages_spoken: ["English", "Czech"])
User.create!(first_name: "Ayita", last_name: "Highjazzy", email: "ayita@ayita.com", password_digest: "", image_url: "", languages_spoken: ["English", "Arabic", "Turkish", "Spanish"])
User.create!(first_name: "Clarious", last_name: "Meow", email: "clarious@clarious.com", password_digest: "", image_url: "", languages_spoken: ["English", "Spanish"])

User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )
User_city.create!(user_id: , city_id: , visited: , lived: , current_living: current_visiting: )

Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
Connection.create!(sender_id: , recipient_id: accepted: )
