City.create!(name: "San Francisco", country: "USA", latitude: 37.7749, longitude: -122.4194)      
City.create!(name: "Shanghai", country: "CHN", latitude: 31.2304, longitude: 121.473)
City.create!(name: "Karachi", country: "PAK", latitude: 24.8607, longitude: 67.0011)
City.create!(name: "Prague", country: "CZE", latitude: 50.0755, longitude: 14.4378)
City.create!(name: "Istanbul", country: "TUR", latitude: 41.0082, longitude: 28.9784)
City.create!(name: "Berlin", country: "DEU", latitude: 52.5200, longitude: 13.4050)
City.create!(name: "New York", country: "USA", latitude: 40.712776 ,longitude: -74.005974)        
City.create!(name: "Chicago", country: "USA", latitude: 41.878113, longitude: -87.629799)         
City.create!(name: "Minneapolis", country: "USA", latitude: 44.977489, longitude: -93.264374)     
City.create!(name: "Los Angeles", country: "USA", latitude: 34.052235, longitude: -118.243683)    
City.create!(name: "Beijing", country: "CHN", latitude: 39.93084, longitude: 116.386337)       
City.create!(name: "Tokyo", country: "JPN", latitude: 35.689487, longitude: 139.691711)           
City.create!(name: "Moscow", country: "RUS", latitude: 55.755825, longitude: 37.617298)           
City.create!(name: "Amman", country: "JOR", latitude: 31.95809, longitude: 35.94581)
City.create!(name: "Dubai", country: "ARE", latitude: 25.204849, longitude: 55.270782)
City.create!(name: "Doha", country: "QAT", latitude: 25.285446, longitude: 51.53104)
City.create!(name: "Cairo", country: "EGY", latitude: 30.04442, longitude: 31.235712)
City.create!(name: "Madrid", country: "ESP", latitude: 40.416775, longitude:  -3.70379)           
City.create!(name: "Barcelona", country: "ESP", latitude: 41.385063, longitude: 2.173404)        
City.create!(name: "Paris", country: "FRA", latitude: 48.856613, longitude: 2.352222)
City.create!(name: "Rome", country: "ITA", latitude: 41.902782, longitude: 12.496365)
City.create!(name: "Warsaw", country: "POL", latitude: 52.229675, longitude: 21.01223)
City.create!(name: "Beirut", country: "LBN", latitude: 33.893791, longitude: 35.501778)           
City.create!(name: "Bishkek", country: "KGZ", latitude: 42.874622, longitude: 74.569763)          
City.create!(name: "Islamabad", country: "PAK", latitude: 33.684422,longitude: 73.047882)        
City.create!(name: "New Delhi", country: "IND", latitude: 28.613939, longitude: 77.209023)        
City.create!(name: "Calcutta", country: "IND", latitude: 22.572645, longitude: 88.363892)         
City.create!(name: "Bombay", country: "IND", latitude: 19.075983, longitude: 72.877655)           
City.create!(name: "Hong Kong", country: "HKG", latitude: 22.28215, longitude: 114.156883)        
City.create!(name: "Bangkok", country: "THA", latitude: 13.756331, longitude: 100.501762)         
City.create!(name: "Kathmandu", country: "NPL", latitude: 27.717245, longitude: 85.323959)       
City.create!(name: "Lisbon", country: "PRT", latitude: 38.722252, longitude: -9.139337)         
City.create!(name: "London", country: "GBR", latitude: 51.507351, longitude: -0.127758)           
City.create!(name: "Mexico City", country: "MEX", latitude: 19.43268, longitude: -99.134209)    
City.create!(name: "Managua", country: "NIC", latitude: 12.13932, longitude: -86.260963)          
City.create!(name: "Quito", country: "ECU", latitude: -0.21495, longitude: -78.513199)
City.create!(name: "Lima", country: "PER", latitude: -12.046373, longitude: -77.042755)           
City.create!(name: "Buenos Aires", country: "ARG", latitude: -34.603683, longitude: -58.381557)  
City.create!(name: "Santiago", country: "CHL", latitude: -33.448891, longitude:  -70.669266)      
City.create!(name: "Montevideo", country: "URY", latitude: -34.901112, longitude: -56.164532)     
City.create!(name: "Rio de Janeiro", country: "BRA", latitude: -22.906847, longitude: -43.172897)
City.create!(name: "São Paulo", country: "BRA", latitude: -23.55052, longitude: -46.633308)      
City.create!(name: "Havana", country: "CUB", latitude: 23.113592, longitude: -82.366592)       
City.create!(name: "Sydney", country: "AUS", latitude: -33.86882, longitude: 151.20929)         
City.create!(name: "Melbourne", country: "AUS", latitude: -37.813629, longitude: 144.963058)      
City.create!(name: "Auckland", country: "NZL", latitude: -36.848461, longitude: 174.763336)       
City.create!(name: "Stockholm", country: "SWE", latitude: 59.329323, longitude: 18.068581)        
City.create!(name: "Cape Town", country: "ZAF", latitude: -33.92487, longitude: 18.424055)      
City.create!(name: "Nairobi", country: "KEN", latitude: -1.292066, longitude: 36.821945)        
City.create!(name: "Lagos", country: "NGA", latitude: 6.524379, longitude: 3.379206)
City.create!(name: "Dakar", country: "SEN", latitude: 14.716677, longitude: -17.467686)         
City.create!(name: "Casablanca", country: "MAR", latitude: 33.596458, longitude: -7.61548)     
City.create!(name: "Lilongwe", country: "MWI", latitude: -13.99572, longitude: 33.759819)       
City.create!(name: "Tehran", country: "IRN", latitude: 35.689198, longitude: 51.388973)           
City.create!(name: "Ramallah", country: "PSE", latitude: 31.862789, longitude: 35.228062)

User.create!(first_name: "Robinho", last_name: "Sotoski", email: "robinho@robinho.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/uploads/14128324071271c853818/3765c625?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80", languages_spoken: "English, Spanish, French, Portuguese, Mandarin, Russian, Turkish")
User.create!(first_name: "Flomario", last_name: "Le Troublebuttz", email: "flomario@flomario.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1493406300581-484b937cdc41?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", languages_spoken: "English, Mandarin")
User.create!(first_name: "Zarru", last_name: "Le Bird", email: "zarru@zarru.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1513338528991-696b7e768c3f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", languages_spoken: "English, Urdu, Hindi, Gujarati")
User.create!(first_name: "Vojta", last_name: "Letalio", email: "vojta@vojta.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1528195135899-cf5d190bb3a1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80", languages_spoken: "English, Czech")
User.create!(first_name: "Ayita", last_name: "Highjazzy", email: "ayita@ayita.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1563515940928-b1bfb1711975?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80", languages_spoken: "English, Arabic, Turkish, Spanish")
User.create!(first_name: "Clarious", last_name: "Meowzer", email: "clarious@clarious.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1498227953826-450c4200f708?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80", languages_spoken: "English, Spanish")
User.create!(first_name: "Lubashka", last_name: "Brodskayayaya", email: "lubashka@lubashka.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1594753765302-8814b8299b4c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80", languages_spoken: "English, Russian")
User.create!(first_name: "Bonita", last_name: "Lee", email: "bonita@bonita.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1582102954017-c0ad7716d644?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=803&q=80", languages_spoken: "English, Polish")
User.create!(first_name: "Priya", last_name: "Dasyeung", email: "priya@priya.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1523433712055-e4d4e4b1f61e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1234&q=80", languages_spoken: "English, Bengali")
User.create!(first_name: "Serenza", last_name: "Cheng", email: "serenza@serenza.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1516209519364-365964646088?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", languages_spoken: "English, Cantonese, Mandarin, Spanish")
User.create!(first_name: "Rainbow", last_name: "Anderson", email: "rainbow@rainbow.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1461237439866-5a557710c921?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1052&q=80", languages_spoken: "English, German, Spanish")
User.create!(first_name: "Annelise", last_name: "Esperanza", email: "annelise@annelise.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1517769160849-02feaecfd6cd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", languages_spoken: "English, Spanish")
User.create!(first_name: "Emilia", last_name: "Philipip", email: "emilia@emilia.com", password: "password", password_confirmation: "password", image_url: "https://unsplash.com/photos/Y6tBl0pTe-g", languages_spoken: "English, Spanish")
User.create!(first_name: "Falyn", last_name: "Zekid", email: "falyn@falyn.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1598974185469-109f0454bddc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80", languages_spoken: "English, Spanish, Swedish")
User.create!(first_name: "Karlina", last_name: "Crafty", email: "karlina@karlina.com", password: "password", password_confirmation: "password", image_url: "https://images.unsplash.com/photo-1565374605948-39525344e745?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80", languages_spoken: "English, Spanish, Korean")

Connection.create!(sender_id: 1, recipient_id: 2, accepted: "true")
Connection.create!(sender_id: 2, recipient_id: 3, accepted: "true")
Connection.create!(sender_id: 3, recipient_id: 4, accepted: "true")
Connection.create!(sender_id: 4, recipient_id: 5, accepted: "false")
Connection.create!(sender_id: 5, recipient_id: 6, accepted: "true")
Connection.create!(sender_id: 6, recipient_id: 7, accepted: "false")
Connection.create!(sender_id: 7, recipient_id: 8, accepted: "false")
Connection.create!(sender_id: 8, recipient_id: 9, accepted: "true")
Connection.create!(sender_id: 9, recipient_id: 10, accepted: "true")
Connection.create!(sender_id: 10, recipient_id: 11, accepted: "true")
Connection.create!(sender_id: 11, recipient_id: 12, accepted: "true")
Connection.create!(sender_id: 12, recipient_id: 13, accepted: "true")
Connection.create!(sender_id: 13, recipient_id: 14, accepted: "true")
Connection.create!(sender_id: 14, recipient_id: 15, accepted: "false")
Connection.create!(sender_id: 15, recipient_id: 1, accepted: "false")
Connection.create!(sender_id: 1, recipient_id: 3, accepted: "true")
Connection.create!(sender_id: 2, recipient_id: 4, accepted: "true")
Connection.create!(sender_id: 3, recipient_id: 5, accepted: "false")
Connection.create!(sender_id: 4, recipient_id: 6, accepted: "true")
Connection.create!(sender_id: 5, recipient_id: 7, accepted: "true")
Connection.create!(sender_id: 6, recipient_id: 8, accepted: "false")
Connection.create!(sender_id: 7, recipient_id: 9, accepted: "false")
Connection.create!(sender_id: 8, recipient_id: 10, accepted: "true")
Connection.create!(sender_id: 9, recipient_id: 11, accepted: "true")
Connection.create!(sender_id: 10, recipient_id: 12, accepted: "false")
Connection.create!(sender_id: 11, recipient_id: 13, accepted: "true")
Connection.create!(sender_id: 12, recipient_id: 14, accepted: "true")
Connection.create!(sender_id: 13, recipient_id: 15, accepted: "true")
Connection.create!(sender_id: 14, recipient_id: 1, accepted: "false")
Connection.create!(sender_id: 15, recipient_id: 2, accepted: "false")
Connection.create!(sender_id: 1, recipient_id: 4, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 5, accepted: "true")
Connection.create!(sender_id: 2, recipient_id: 5, accepted: "true")
Connection.create!(sender_id: 2, recipient_id: 6, accepted: "true")
Connection.create!(sender_id: 3, recipient_id: 7, accepted: "true")
Connection.create!(sender_id: 3, recipient_id: 8, accepted: "true")
Connection.create!(sender_id: 4, recipient_id: 9, accepted: "false")
Connection.create!(sender_id: 4, recipient_id: 10, accepted: "false")
Connection.create!(sender_id: 5, recipient_id: 11, accepted: "true")
Connection.create!(sender_id: 5, recipient_id: 12, accepted: "true")
Connection.create!(sender_id: 6, recipient_id: 13, accepted: "true")
Connection.create!(sender_id: 6, recipient_id: 14, accepted: "true")
Connection.create!(sender_id: 7, recipient_id: 15, accepted: "true")
Connection.create!(sender_id: 7, recipient_id: 10, accepted: "true")
Connection.create!(sender_id: 8, recipient_id: 11, accepted: "false")
Connection.create!(sender_id: 8, recipient_id: 12, accepted: "false")
Connection.create!(sender_id: 9, recipient_id: 13, accepted: "true")
Connection.create!(sender_id: 9, recipient_id: 14, accepted: "true")
Connection.create!(sender_id: 10, recipient_id: 15, accepted: "false")
Connection.create!(sender_id: 10, recipient_id: 2, accepted: "true")
Connection.create!(sender_id: 11, recipient_id: 2, accepted: "true")
Connection.create!(sender_id: 11, recipient_id: 3, accepted: "true")
Connection.create!(sender_id: 12, recipient_id: 4, accepted: "true")
Connection.create!(sender_id: 12, recipient_id: 6, accepted: "false")
Connection.create!(sender_id: 13, recipient_id: 7, accepted: "false")
Connection.create!(sender_id: 13, recipient_id: 8, accepted: "true")
Connection.create!(sender_id: 14, recipient_id: 2, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 6, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 7, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 8, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 9, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 10, accepted: "false")
Connection.create!(sender_id: 1, recipient_id: 11, accepted: "false")
Connection.create!(sender_id: 1, recipient_id: 12, accepted: "true")
Connection.create!(sender_id: 1, recipient_id: 13, accepted: "false")
Connection.create!(sender_id: 1, recipient_id: 14, accepted: "false")
Connection.create!(sender_id: 1, recipient_id: 15, accepted: "true")
